version: "2"

services:
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_DATABASE=appdb
      - MYSQL_PASSWORD=password
    volumes:
      - ./.docker/db:/var/lib/mysql

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 8181:80
    volumes:
        - ./.docker/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
  myapp:
    tty: true
    build: 'docker/apache2'
    depends_on:
      - mariadb
    ports:
      - 81:80
    volumes:
      - ./.docker/apache2:/etc/apache2/sites-available
      - ./:/var/www/html
    # privileged: true # Privileged mode could be required to run this container under Windows
